# Generated by Django 2.2.6 on 2019-11-09 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('education_lvl', models.IntegerField()),
                ('annual_income', models.IntegerField()),
                ('net_worth', models.IntegerField()),
                ('known_expenses', models.IntegerField()),
                ('possible_expenses', models.IntegerField()),
                ('liquidity_needs', models.IntegerField()),
                ('investment_objectives', models.IntegerField()),
                ('risk_tolerance', models.IntegerField()),
                ('last_reviewed', models.DateField()),
                ('reviewed_notes', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='signer',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='signer',
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.DeleteModel(
            name='Signer',
        ),
    ]
