# Generated by Django 2.2.6 on 2019-11-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191109_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
