# Generated by Django 2.2.6 on 2019-11-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_questions_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='investment_experience',
            field=models.IntegerField(default=0),
        ),
    ]
