# Generated by Django 2.2.6 on 2019-11-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191110_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
