# Generated by Django 2.2.6 on 2019-11-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191110_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='at_risk',
            field=models.IntegerField(default=0),
        ),
    ]
